import os
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# Get the redirect_uri from the environment variable
redirect_uri = os.environ['REDIRECT_URI']

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(client_id=os.environ['4a6221cb520a4097a6d0978642daa986'],
                                               client_secret=os.environ['9895ce77e9564279878d4eb38c7987c8'],
                                               redirect_uri=redirect_uri,
                                               scope="playlist-modify-public"))

def save_playlist_to_spotify(prompt, playlist):
    user_id = sp.current_user()["id"]
    playlist_name = f"{prompt} playlist"
    new_playlist = sp.user_playlist_create(user_id, playlist_name, public=True, description=f"Generated by SpotAI for prompt: {prompt}")
    playlist_id = new_playlist["id"]
    
    # Add tracks to the playlist
    sp.user_playlist_add_tracks(user_id, playlist_id, playlist)

    return new_playlist["external_urls"]["spotify"]
